//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/edgebug.html
halflife.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
maps/edgebug.bsp
