// .res generated by gchimp ResMake
// https://github.com/khanghugo/gchimp
// Generated date: Sat, 28 Jun 2025 16:16:04 +0200
// Entry count: 21

// models 
models/v4r/v4rious/env_shroom4.mdl
models/v4r/v4rious/env_shroom4R.mdl
models/v4r/v4rious/fnv_fungus02.mdl
models/v4r/v4rious/fnv_fungus02R.mdl
models/v4r/v4rious/pc_Mushroom_Mesh.mdl
models/v4r/v4rious/pc_Mushroom_MeshR.mdl
models/v4r/v4rious/powerline0.mdl
models/v4r/v4rious/reflection2.mdl
models/v4r/v4rious/scatterd_trees0.mdl
models/v4r/v4rious/skybox0.mdl
models/v4r/v4rious/terrain.mdl
models/v4r/v4rious/trees.mdl

// sound
sound/v4r/amb_waterdrip.wav
sound/v4r/outdoor_ambience.wav

// gfx
gfx/env/arcssbk.tga
gfx/env/arcssdn.tga
gfx/env/arcssft.tga
gfx/env/arcsslf.tga
gfx/env/arcssrt.tga
gfx/env/arcssup.tga

// sprites
sprites/v4r/light.spr
